### ISSUE TITLE
Distribution: sign the app

### ISSUE THREAD

**Issue by compartia** [kestreltechnology/electron-kt-advance#43]
refer
https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by mrbkt** [comment]
On `issue43` branch:

1. Exported my own certificate from Xcode
1. Base64 encoded
1. Uploaded to company's AWS account for S3 access
1. Used Travis encryption to post `CSC_LINK` and `CSC_KEY_PASSWORD` to `.travis.yml`

Give it a try for signing.

**Comment by mrbkt** [comment]
Code signing appears to work with the Mac development certificate.  Travis warns not suitable for production; so noted, will generate a new signing certificate with proper CA.  

Travis build complaining about (a) typescript issue, and (b) deploy authorization.  Did the bug fixes merge break the build settings?

**Comment by compartia** [comment]
the most recent branch which is called "syntax-highlight" is green now (for some reason I'm hesitating to merge it into master however you can use it for signing conf.)

**Comment by mrbkt** [comment]
I've ordered a real code-signing certificate.  When it turns up I'll post the certificate and redo the code signing settings.

**Comment by mrbkt** [comment]
I installed a DigiCert code-signing certificate because we use DigiCert for SSL certificates.  But I now see that perhaps that is not good enough for a Travis OS X build, something having to do with the Apple Gatekeeper.  The application builds and passes Travis, but the app is not signed despite successfully retrieving the certificate.  

s/a [OS X code signing error of Travis CI](https://github.com/electron-userland/electron-builder/issues/398).  

From [build #202](https://travis-ci.org/kestreltechnology/electron-kt-advance/builds/257453164):

```
Warning: App is not signed: cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://github.com/electron-userland/electron-builder/wiki/Code-Signing
All identities:
  1) 22BBE53D94D244B5041C18A3B0CC4E63663F50E0 "Kestrel Technology LLC" (CSSMERR_TP_NOT_TRUSTED)
     1 identities found
  Valid identities only
     0 valid identities found
Building macOS zip
Building DMG
```

**Comment by compartia** [comment]
the trick was to 
change 
`"release": "build",`
to
`"release": "export CSC_LINK=${CSC_LINK} && export CSC_KEY_PASSWORD=${CSC_KEY_PASSWORD} && build"`

also, the value of CSC_LINK must be put in quotes even if set via Travis-CI UI. 
<img width="178" alt="screen shot 2018-08-10 at 17 11 04" src="https://user-images.githubusercontent.com/7677437/43962478-77e17990-9cc0-11e8-993e-e08789677924.png">
